version: '2.27'

services:
  postgres:
    container_name: pardalCash-pg
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pardalCash
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
